In [12]:
!pip install -q langchain langchain-community langchain-huggingface langchain-text-splitters faiss-cpu pypdf sentence-transformers transformers accelerate langgraph
!mkdir -p docs

In [13]:
import glob
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

docs = []
for f in glob.glob("docs/*.pdf"):
    try:
        docs += PyPDFLoader(f).load()
        print("loaded:", f)
    except Exception as e:
        print("SKIPPED:", f, "|", type(e).__name__)

chunks = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100).split_documents(docs)
print(len(docs), "pages ->", len(chunks), "chunks")

loaded: docs/16th ICCCNT 2025_submission_128_paper_v2.pdf
loaded: docs/Unit_2 Notes.pdf
loaded: docs/Unit_1 Notes.pdf
60 pages -> 182 chunks

In [14]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

emb = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
db = FAISS.from_documents(chunks, emb)
retriever = db.as_retriever(search_kwargs={"k": 4})

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [15]:
import torch
from transformers import pipeline

print("GPU available:", torch.cuda.is_available())   # must say True

gen = pipeline("text-generation", model="Qwen/Qwen2.5-3B-Instruct",
               device_map="auto", torch_dtype=torch.float16)
print("Model device:", gen.model.device, "| dtype:", gen.model.dtype)

def llm(system, user, max_new_tokens=120):
    msgs = [{"role": "system", "content": system}, {"role": "user", "content": user}]
    out = gen(msgs, return_full_text=False, max_new_tokens=max_new_tokens, do_sample=False)[0]["generated_text"]
    return out if isinstance(out, str) else out[-1]["content"]

GPU available: True

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Model device: cuda:0 | dtype: torch.float16

In [16]:
from typing import TypedDict, List
from langgraph.graph import StateGraph, END

class State(TypedDict):
    question: str
    query: str
    docs: List[str]
    relevant: bool
    answer: str
    tries: int
    route: str

def route_node(s):
    r = llm("Reply with exactly one word: 'retrieve' if the question needs information from the user's documents, or 'direct' if it is general knowledge or small talk.", s["question"], 5)
    return {"route": "retrieve" if "retrieve" in r.lower() else "direct", "query": s["question"], "tries": 0}

def retrieve_node(s):
    hits = retriever.invoke(s["query"])
    return {"docs": [h.page_content for h in hits]}

def grade_node(s):
    ctx = "\n---\n".join(s["docs"])[:3000]
    r = llm("Reply with exactly one word: 'yes' if the context contains information that helps answer the question, otherwise 'no'.", f"Question: {s['question']}\n\nContext:\n{ctx}", 5)
    return {"relevant": "yes" in r.lower()}

def rewrite_node(s):
    q = llm("Rewrite the question as a short keyword-style search query that would work better for document retrieval. Output only the query.", s["question"], 30)
    return {"query": q.strip(), "tries": s["tries"] + 1}

def generate_node(s):
    ctx = "\n\n".join(s["docs"])
    a = llm("Answer only using the context. If the answer is not in the context, say you don't know.", f"Context:\n{ctx}\n\nQuestion: {s['question']}", 120)
    return {"answer": a}

def direct_node(s):
    return {"answer": llm("You are a helpful assistant. Answer briefly.", s["question"], 200)}

In [17]:
g = StateGraph(State)
g.add_node("route", route_node)
g.add_node("retrieve", retrieve_node)
g.add_node("grade", grade_node)
g.add_node("rewrite", rewrite_node)
g.add_node("generate", generate_node)
g.add_node("direct", direct_node)

g.set_entry_point("route")
g.add_conditional_edges("route", lambda s: s["route"], {"retrieve": "retrieve", "direct": "direct"})
g.add_edge("retrieve", "grade")
g.add_conditional_edges(
    "grade",
    lambda s: "generate" if (s["relevant"] or s["tries"] >= 2) else "rewrite",
    {"generate": "generate", "rewrite": "rewrite"},
)
g.add_edge("rewrite", "retrieve")
g.add_edge("generate", END)
g.add_edge("direct", END)

app = g.compile()

In [18]:
def run(q):
    steps = []
    final = None
    for event in app.stream({"question": q}):
        for node, update in event.items():
            steps.append(node)
            final = {**(final or {}), **update}
    return final["answer"], steps, final.get("tries", 0)

for q in ["What accuracy did the model achieve?", "What is the capital of France?"]:
    ans, steps, retries = run(q)
    print(q, "\n steps:", " -> ".join(steps), "| retries:", retries, "\n answer:", ans, "\n")

What accuracy did the model achieve?
 steps: route -> retrieve -> grade -> generate | retries: 0
 answer: The model achieved an overall accuracy of 93%.

What is the capital of France?
 steps: route -> direct | retries: 0
 answer: Paris

In [19]:
hits = retriever.invoke("What accuracy did the model achieve?")
for h in hits:
    print(h.metadata.get("source"), "p", h.metadata.get("page"), "|", h.page_content[:300].replace("\n", " "))
    print("---")

docs/16th ICCCNT 2025_submission_128_paper_v2.pdf p 3 | cation. V. R ESULTS AND ANALYSIS The system was tested using a dataset of 3112 images captured from cattle in varying conditions. Key performance metrics were examined in the study to include the following: A. Key Performance Metrics • Accuracy: The system achieved an overall accuracy of 93%, classi
---
docs/16th ICCCNT 2025_submission_128_paper_v2.pdf p 4 | model generalisation. Without preprocessing: • Accuracy fell from 93% to 86% • F1 Score declined from 93% (average) to 85% (aver- age).This shows that data preprocessing is primarily con- cerned with enhancing data quality and model stability. B. Without Fine-Tuning the CNN (Utilizing Raw Pre-traine
---
docs/16th ICCCNT 2025_submission_128_paper_v2.pdf p 3 | B. Model Training A Convolutional Neural Network model with AlexNet ar- chitecture is employed to make the prediction of LSD severity. The model is trained with the Adam optimizer and the cross- entropy loss function. The data is split into a training set, a validation set, and a test set (for e.g.
---
docs/16th ICCCNT 2025_submission_128_paper_v2.pdf p 2 | techniques (e.g., rotation, flipping, scaling) to increase data variability and model robustness. 1) Real-Time Pre-processing Pipeline: • Noise Reduction:Gaussian filtering is applied to suppress background noise and improve the clarity of relevant features such as skin lesions. • Normalization:All
---

In [20]:
tests = [
    ("What accuracy did the model achieve?", "93", "doc"),
    ("Which architecture was used?", "CNN", "doc"),
    # add your own "doc" questions here
    ("What is the capital of France?", "paris", "general"),
    ("Black hat hackers are?", "cybercriminals", "doc"),
    ("Who wrote Romeo and Juliet?", "shakespeare", "general"),
    ("What is 12 times 12?", "144", "general"),
    ("What is the author's favourite food?", "", "unanswerable"),
    ("What type of cyber attack was conducted on Canada’s Parliament in September 2023?", "DDoS Attack", "doc"),
    ("What is the first stage in ethical hacking","Reconnaissance","doc"),
    ("Whats is the weather on the day author was born","","unanswerable")
]

def plain_rag(q):
    ctx = "\n\n".join(h.page_content for h in retriever.invoke(q))
    return llm("Answer only using the context. If the answer is not in the context, say you don't know.",
               f"Context:\n{ctx}\n\nQuestion: {q}", 120)

In [21]:
def correct(ans, kw, kind):
    a = ans.lower()
    if kind == "unanswerable":
        return any(p in a for p in ["don't know", "do not know", "not mentioned", "no information", "cannot"])
    return kw.lower() in a

rows = []
for q, kw, kind in tests:
    p_ans = plain_rag(q)
    a_ans, steps, retries = run(q)
    routed_right = ("direct" in steps) == (kind == "general")
    rows.append({
        "type": kind, "question": q,
        "plain_ok": correct(p_ans, kw, kind),
        "agent_ok": correct(a_ans, kw, kind),
        "routed_right": routed_right,
        "retries": retries,
        "path": " > ".join(steps),
    })

import pandas as pd
df = pd.DataFrame(rows)
print(df[["type", "plain_ok", "agent_ok", "routed_right", "retries"]].groupby("type").mean())
print("\nOverall plain RAG :", df.plain_ok.mean())
print("Overall agentic   :", df.agent_ok.mean())
print("Routing accuracy  :", df.routed_right.mean())
print("Avg retries       :", df.retries.mean())
df

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

              plain_ok  agent_ok  routed_right   retries
type
doc                0.2       0.4      0.200000  0.000000
general            0.0       1.0      0.666667  0.666667
unanswerable       1.0       0.5      0.500000  1.000000

Overall plain RAG : 0.3
Overall agentic   : 0.6
Routing accuracy  : 0.4
Avg retries       : 0.4

,type,question,plain_ok,agent_ok,routed_right,retries,path
0,doc,What accuracy did the model achieve?,True,True,True,0,route > retrieve > grade > generate
1,doc,Which architecture was used?,False,False,False,0,route > direct
2,general,What is the capital of France?,False,True,True,0,route > direct
3,doc,Black hat hackers are?,False,False,False,0,route > direct
4,general,Who wrote Romeo and Juliet?,False,True,True,0,route > direct
5,general,What is 12 times 12?,False,True,False,2,route > retrieve > grade > rewrite > retrieve ...
6,unanswerable,What is the author's favourite food?,True,True,True,2,route > retrieve > grade > rewrite > retrieve ...
7,doc,What type of cyber attack was conducted on Can...,False,False,False,0,route > direct
8,doc,What is the first stage in ethical hacking,False,True,False,0,route > direct
9,unanswerable,Whats is the weather on the day author was born,True,False,False,0,route > direct

In [22]:
df.to_csv("eval_v1.csv", index=False)
print("saved")

saved

In [23]:
  from google.colab import files
  files.download("eval_v1.csv")

In [24]:
import time, pandas as pd
rows = []
for i, (q, kw, kind) in enumerate(tests):
    t = time.time()
    p_ans = plain_rag(q)
    a_ans, steps, retries = run(q)
    rows.append({
        "type": kind, "question": q,
        "plain_ok": correct(p_ans, kw, kind),
        "agent_ok": correct(a_ans, kw, kind),
        "routed_right": ("direct" in steps) == (kind == "general"),
        "retries": retries,
        "path": " > ".join(steps),
        "plain_answer": p_ans, "agent_answer": a_ans,
    })
    print(f"{i+1}/{len(tests)} done in {time.time()-t:.0f}s")

df = pd.DataFrame(rows)
df.to_csv("eval_v2.csv", index=False)
print(df[["type", "plain_ok", "agent_ok", "routed_right", "retries"]].groupby("type").mean())
print("Plain:", df.plain_ok.mean(), "| Agent:", df.agent_ok.mean(), "| Routing:", df.routed_right.mean())
df[["question", "path", "agent_ok", "agent_answer"]]

1/10 done in 6s
2/10 done in 7s
3/10 done in 2s
4/10 done in 7s
5/10 done in 2s
6/10 done in 5s
7/10 done in 3s
8/10 done in 3s
9/10 done in 5s
10/10 done in 3s
              plain_ok  agent_ok  routed_right   retries
type
doc                0.2       0.4      0.200000  0.000000
general            0.0       1.0      0.666667  0.666667
unanswerable       1.0       0.5      0.500000  1.000000
Plain: 0.3 | Agent: 0.6 | Routing: 0.4

,question,path,agent_ok,agent_answer
0,What accuracy did the model achieve?,route > retrieve > grade > generate,True,The model achieved an overall accuracy of 93%.
1,Which architecture was used?,route > direct,False,The architecture used is not specified in the ...
2,What is the capital of France?,route > direct,True,Paris
3,Black hat hackers are?,route > direct,False,Black hat hackers are individuals who exploit ...
4,Who wrote Romeo and Juliet?,route > direct,True,William Shakespeare wrote Romeo and Juliet.
5,What is 12 times 12?,route > retrieve > grade > rewrite > retrieve ...,True,12 times 12 equals 144.
6,What is the author's favourite food?,route > retrieve > grade > rewrite > retrieve ...,True,I don't know.
7,What type of cyber attack was conducted on Can...,route > direct,False,A cyber attack involving ransomware was conduc...
8,What is the first stage in ethical hacking,route > direct,True,The first stage in ethical hacking is usually ...
9,Whats is the weather on the day author was born,route > direct,False,I don't have access to specific personal detai...

In [25]:
df.to_csv("eval_v1.csv", index=False)
print("saved")

saved

In [26]:
DOC_TOPICS = "ethical hacking: types of hackers, cyber attacks, stages of ethical hacking,footprinting, types of social engineering, evation techniques, Automated detection of lumpy skin disease in cattle using RFID and CNN techniques "

def route_node(s):
    system = (
        f"The user has uploaded documents about: {DOC_TOPICS}.\n"
        "Reply with exactly one word.\n"
        "'retrieve' if the question is about those topics in any way.\n"
        "'direct' ONLY if the question is clearly unrelated (geography, maths, literature, small talk).\n"
        "If unsure, reply 'retrieve'."
    )
    r = llm(system, s["question"], 5)
    return {"route": "direct" if "direct" in r.lower() else "retrieve",
            "query": s["question"], "tries": 0}

def direct_node(s):
    return {"answer": llm("Answer briefly. If the question asks for personal or unknowable information, say you don't know.",
                          s["question"], 120)}

g = StateGraph(State)
g.add_node("route", route_node)
g.add_node("retrieve", retrieve_node)
g.add_node("grade", grade_node)
g.add_node("rewrite", rewrite_node)
g.add_node("generate", generate_node)
g.add_node("direct", direct_node)
g.set_entry_point("route")
g.add_conditional_edges("route", lambda s: s["route"], {"retrieve": "retrieve", "direct": "direct"})
g.add_edge("retrieve", "grade")
g.add_conditional_edges("grade", lambda s: "generate" if (s["relevant"] or s["tries"] >= 2) else "rewrite",
                        {"generate": "generate", "rewrite": "rewrite"})
g.add_edge("rewrite", "retrieve")
g.add_edge("generate", END)
g.add_edge("direct", END)
app = g.compile()

print(route_node({"question": "Black hat hackers are?"})["route"])
print(route_node({"question": "What is 12 times 12?"})["route"])

retrieve
direct

In [27]:
def correct(ans, kw, kind):
    a = ans.lower()
    if kind == "unanswerable":
        phrases = ["don't know", "do not know", "not mentioned", "no information", "cannot",
                   "don't have access", "do not have access", "not specified", "not available", "unable to"]
        return any(p in a for p in phrases)
    return kw.lower() in a

In [28]:
import time, pandas as pd
rows = []
for i, (q, kw, kind) in enumerate(tests):
    t = time.time()
    p_ans = plain_rag(q)
    a_ans, steps, retries = run(q)
    rows.append({
        "type": kind, "question": q,
        "plain_ok": correct(p_ans, kw, kind),
        "agent_ok": correct(a_ans, kw, kind),
        "routed_right": ("direct" in steps) == (kind == "general"),
        "retries": retries,
        "path": " > ".join(steps),
        "plain_answer": p_ans, "agent_answer": a_ans,
    })
    print(f"{i+1}/{len(tests)} done in {time.time()-t:.0f}s")

df = pd.DataFrame(rows)
df.to_csv("eval_v2.csv", index=False)
print(df[["type", "plain_ok", "agent_ok", "routed_right", "retries"]].groupby("type").mean())
print("Plain:", df.plain_ok.mean(), "| Agent:", df.agent_ok.mean(), "| Routing:", df.routed_right.mean())
df[["question", "path", "agent_ok", "agent_answer"]]

1/10 done in 4s
2/10 done in 6s
3/10 done in 3s
4/10 done in 12s
5/10 done in 2s
6/10 done in 2s
7/10 done in 2s
8/10 done in 4s
9/10 done in 6s
10/10 done in 4s
              plain_ok  agent_ok  routed_right  retries
type
doc                0.2       0.2           0.6      0.8
general            0.0       1.0           1.0      0.0
unanswerable       1.0       1.0           0.0      0.0
Plain: 0.3 | Agent: 0.6 | Routing: 0.6

,question,path,agent_ok,agent_answer
0,What accuracy did the model achieve?,route > retrieve > grade > generate,True,The model achieved an overall accuracy of 93%.
1,Which architecture was used?,route > direct,False,I need more specific details to answer this qu...
2,What is the capital of France?,route > direct,True,The capital of France is Paris.
3,Black hat hackers are?,route > retrieve > grade > rewrite > retrieve ...,False,"Based on the provided context, black hat hacke..."
4,Who wrote Romeo and Juliet?,route > direct,True,William Shakespeare wrote Romeo and Juliet.
5,What is 12 times 12?,route > direct,True,144
6,What is the author's favourite food?,route > direct,True,I don't know the author's favorite food as I d...
7,What type of cyber attack was conducted on Can...,route > direct,False,I don't know the specific type of cyber attack...
8,What is the first stage in ethical hacking,route > retrieve > grade > rewrite > retrieve ...,False,The context provided does not explicitly state...
9,Whats is the weather on the day author was born,route > direct,True,I don't know the specific weather on the day t...

In [29]:
bad = df[(df.type == "doc") & (~df.agent_ok)]
for _, r in bad.iterrows():
    print("Q:", r.question)
    print("PATH:", r.path)
    print("KEYWORD:", [kw for q, kw, k in tests if q == r.question])
    print("AGENT ANSWER:", r.agent_answer)
    print("TOP CHUNKS:")
    for h in retriever.invoke(r.question):
        print("  - p", h.metadata.get("page"), "|", h.page_content[:200].replace("\n", " "))
    print("=" * 80)

Q: Which architecture was used?
PATH: route > direct
KEYWORD: ['CNN']
AGENT ANSWER: I need more specific details to answer this question accurately. Different types of architectures (like microservices, monolithic, serverless) are used depending on various factors such as project requirements, team expertise, and scalability needs. Without knowing the context of a particular system or application, I can't specify which one was used.
TOP CHUNKS:
  - p 0 | 2. Active Footprinting  Directly engaging with the target system to gather details.  Ex: Port scanning, traceroute, and banner grabbing using tools like Nmap and Netcat.  3. Search Engine Footprinting
  - p 14 | ➢ Firewall Protection – Block ports 137, 138, 139, 445, restrict ICMP.  ➢ Secure System Info – Hide OS details, restrict AD enumeration.  ➢ Monitor & Audit – Use IDS/IPS, check logs, conduct security
  - p 8 | services from a system. In this phase, the attacker creates an active connection to the system and performs directed  queries to gain more information about the target. The gathered information is use
  - p 5 | • Nmap – Port and network scanning.  • Angry IP Scanner – Simple IP and port scanner.  • Nessus – Vulnerability assessment.  • Nikto – Web server scanning.  • OpenVAS – Open-source vulnerability scann
================================================================================
Q: Black hat hackers are?
PATH: route > retrieve > grade > rewrite > retrieve > grade > rewrite > retrieve > grade > generate
KEYWORD: ['cybercriminals']
AGENT ANSWER: Based on the provided context, black hat hackers are malicious users who carry out attacks without authorization. The context does not explicitly define black hat hackers but contrasts them with ethical hackers (red team members) who work within legal boundaries to improve security and report vulnerabilities. Therefore, we can infer that black hat hackers are those who engage in unauthorized and harmful cyber activities.
TOP CHUNKS:
  - p 9 | 4. Insider Attacks  o These attacks are carried out by individuals with legitimate access  to systems, such as employees or contractors, who misuse their  privileges.
  - p 4 | Red, Blue, and Purple Teams in Cybersecurity  1. Red Team consists of ethical hackers (offensive security experts) who  simulate real-world cyberattacks. Their goal is to identify vulnerabilities  by
  - p 1 | improving the security and defending the systems from attacks by malicious  users.   Ethical hackers are expected to report all the vulnerabilities and weakness  found during the process to the manage
  - p 6 | Ethical Hacking             PES University
================================================================================
Q: What type of cyber attack was conducted on Canada’s Parliament in September 2023?
PATH: route > direct
KEYWORD: ['DDoS Attack']
AGENT ANSWER: I don't know the specific type of cyber attack that occurred on Canada's Parliament in September 2023 as I don't have access to real-time or current event information.
TOP CHUNKS:
  - p 10 | o Examples: Data theft, privilege abuse, and sabotage.  5. Distribution Attacks  o These attacks occur when malicious components are introduced  into hardware or software before they reach the end use
  - p 15 | Ethical Hacking             PES University
  - p 9 | 4. Insider Attacks  o These attacks are carried out by individuals with legitimate access  to systems, such as employees or contractors, who misuse their  privileges.
  - p 4 | Red, Blue, and Purple Teams in Cybersecurity  1. Red Team consists of ethical hackers (offensive security experts) who  simulate real-world cyberattacks. Their goal is to identify vulnerabilities  by
================================================================================
Q: What is the first stage in ethical hacking
PATH: route > retrieve > grade > rewrite > retrieve > grade > rewrite > retrieve > grade > generate
KEYWORD: ['Reconnaissance']
AGENT ANSWER: The context provided does not explicitly state the first stage in ethical hacking. Therefore, I cannot determine the first stage based solely on the given information.
TOP CHUNKS:
  - p 1 | What is Ethical Hacking?   Ethical Hacking sometimes called as Penetration Testing is an act of  intruding/penetrating into system or networks to find out threats,  vulnerabilities in those systems wh
  - p 1 | Ethical Hacking   What is Hacking?   Hacking is the process of identifying and exploiting weakness in a system or a  network to gain unauthorized access to data and system resources.   or  It is an un
  - p 28 | Ethical Hacking             PES University
  - p 2 | Why Ethical Hacking is Necessary  • prevent hackers  • uncover vulnerabilities  • strengthen an organization’s security posture  • avoid security breaches  • Safeguard customer data  • Enhance securit
================================================================================

In [30]:
def correct(ans, kw, kind):
    a = ans.lower()
    if kind == "unanswerable":
        phrases = ["don't know", "do not know", "not mentioned", "no information", "cannot",
                   "don't have access", "do not have access", "not specified", "not available", "unable to"]
        return any(p in a for p in phrases)
    return any(k.strip().lower() in a for k in kw.split("|"))

In [31]:
retriever = db.as_retriever(search_kwargs={"k": 6})

tests = [
    # document questions
    ("What accuracy did the model achieve?", "93", "doc"),
    ("Black hat hackers are?", "malicious|unauthorized|cybercriminal", "doc"),
    ("What type of cyber attack was conducted on Canada’s Parliament in September 2023?", "DDoS|denial", "doc"),
    ("What is the first stage in ethical hacking", "reconnaissance|footprinting", "doc"),
    ("Which tool is used for port and network scanning?", "nmap", "doc"),
    ("What does the Red Team consist of?", "ethical hackers", "doc"),
    ("Which ports should a firewall block to protect against enumeration?", "445|139", "doc"),
    ("What are insider attacks?", "legitimate access|employees", "doc"),
    # general questions
    ("What is the capital of France?", "paris", "general"),
    ("Who wrote Romeo and Juliet?", "shakespeare", "general"),
    ("What is 12 times 12?", "144", "general"),
    # unanswerable questions
    ("What is the author's favourite food?", "", "unanswerable"),
    ("Whats is the weather on the day author was born", "", "unanswerable"),
]
print(len(tests), "tests")

13 tests

In [32]:
import time, pandas as pd
rows = []
for i, (q, kw, kind) in enumerate(tests):
    t = time.time()
    p_ans = plain_rag(q)
    a_ans, steps, retries = run(q)
    rows.append({
        "type": kind, "question": q,
        "plain_ok": correct(p_ans, kw, kind),
        "agent_ok": correct(a_ans, kw, kind),
        "routed_right": ("direct" in steps) == (kind == "general"),
        "retries": retries,
        "path": " > ".join(steps),
        "plain_answer": p_ans, "agent_answer": a_ans,
    })
    print(f"{i+1}/{len(tests)} done in {time.time()-t:.0f}s")

df = pd.DataFrame(rows)
df.to_csv("eval_v2.csv", index=False)
print(df[["type", "plain_ok", "agent_ok", "routed_right", "retries"]].groupby("type").mean())
print("Plain:", df.plain_ok.mean(), "| Agent:", df.agent_ok.mean(), "| Routing:", df.routed_right.mean())
df[["question", "path", "agent_ok", "agent_answer"]]

1/13 done in 4s
2/13 done in 8s
3/13 done in 4s
4/13 done in 6s
5/13 done in 3s
6/13 done in 6s
7/13 done in 7s
8/13 done in 4s
9/13 done in 2s
10/13 done in 2s
11/13 done in 2s
12/13 done in 2s
13/13 done in 5s
              plain_ok  agent_ok  routed_right  retries
type
doc           0.625000     0.625         0.875      1.0
general       0.333333     1.000         1.000      0.0
unanswerable  1.000000     1.000         0.000      0.0
Plain: 0.6153846153846154 | Agent: 0.7692307692307693 | Routing: 0.7692307692307693

,question,path,agent_ok,agent_answer
0,What accuracy did the model achieve?,route > retrieve > grade > generate,True,The model achieved an overall accuracy of 93%.
1,Black hat hackers are?,route > retrieve > grade > rewrite > retrieve ...,False,Black hat hackers are those who engage in unet...
2,What type of cyber attack was conducted on Can...,route > direct,False,I don't know the specific type of cyber attack...
3,What is the first stage in ethical hacking,route > retrieve > grade > rewrite > retrieve ...,False,"The first stage in ethical hacking, according ..."
4,Which tool is used for port and network scanning?,route > retrieve > grade > generate,True,Nmap is used for port and network scanning.
5,What does the Red Team consist of?,route > retrieve > grade > rewrite > retrieve ...,True,The Red Team consists of ethical hackers (offe...
6,Which ports should a firewall block to protect...,route > retrieve > grade > rewrite > retrieve ...,True,"Ports 137, 138, 139, and 445 should be blocked..."
7,What are insider attacks?,route > retrieve > grade > generate,True,Insider attacks are carried out by individuals...
8,What is the capital of France?,route > direct,True,The capital of France is Paris.
9,Who wrote Romeo and Juliet?,route > direct,True,William Shakespeare wrote Romeo and Juliet.
10,What is 12 times 12?,route > direct,True,144
11,What is the author's favourite food?,route > direct,True,I don't know the author's favorite food as I d...
12,Whats is the weather on the day author was born,route > direct,True,I don't know the specific weather on the day t...

In [33]:
for _, r in df[~df.agent_ok].iterrows():
    print("Q:", r.question)
    print("PATH:", r.path)
    print("AGENT:", r.agent_answer)
    print("PLAIN:", r.plain_answer)
    print("=" * 70)

m = df[df.type != "unanswerable"]
print("Routing (doc+general):", m.routed_right.mean())
print(df[(df.type == "doc") & (df.plain_ok != df.agent_ok)][["question", "plain_ok", "agent_ok"]])

for term in ["canada", "ddos", "reconnaissance", "footprinting"]:
    print(term, "-> pages", sorted({c.metadata.get("page") for c in chunks if term in c.page_content.lower()}))

Q: Black hat hackers are?
PATH: route > retrieve > grade > rewrite > retrieve > grade > rewrite > retrieve > grade > generate
AGENT: Black hat hackers are those who engage in unethical hacking activities, typically aiming to exploit vulnerabilities for personal gain or causing damage rather than improving security or defending systems. Based on the provided context, they do not report vulnerabilities found during their activities to management, unlike ethical hackers. They also carry out attacks without authorization, which is illegal and harmful.
PLAIN: Based on the provided context, black hat hackers are not explicitly defined or described. Therefore, I do not have enough information to accurately answer what black hat hackers are.
======================================================================
Q: What type of cyber attack was conducted on Canada’s Parliament in September 2023?
PATH: route > direct
AGENT: I don't know the specific type of cyber attack that occurred on Canada's Parliament in September 2023 as I don't have access to real-time or current event information.
PLAIN: I don't know. The provided context does not contain any information about a cyber attack on Canada's Parliament in September 2023.
======================================================================
Q: What is the first stage in ethical hacking
PATH: route > retrieve > grade > rewrite > retrieve > grade > rewrite > retrieve > grade > generate
AGENT: The first stage in ethical hacking, according to the provided context, is "Locate Nodes". This involves identifying the devices, servers, or endpoints in the network that need to be assessed.
PLAIN: The first stage in ethical hacking, as described in the given context, is "Locate Nodes". This involves identifying the devices, servers, or endpoints in the network that need to be assessed.
======================================================================
Routing (doc+general): 0.9090909090909091
Empty DataFrame
Columns: [question, plain_ok, agent_ok]
Index: []
canada -> pages []
ddos -> pages [15, 18]
reconnaissance -> pages [4, 5, 7, 10, 13]
footprinting -> pages [0, 1, 2, 3]

In [34]:
for term in ["locate nodes", "reconnaissance"]:
    print("=====", term)
    for c in [c for c in chunks if term in c.page_content.lower()][:3]:
        print("p", c.metadata.get("page"), "|", c.page_content[:350].replace("\n", " "))
        print("--")

===== locate nodes
p 27 | Ethical Hacking             PES University                                                                                                                                                                   Department of CSE      This process ensures that security risks in a network are identified and addressed systematically.    1. Locate Nodes: Ide
--
===== reconnaissance
p 4 | Ethical Hacking             PES University                                                                                                                                                                   Department of CSE  Purpose:  • Identifies network infrastructure.  • Detects security misconfigurations.  • Helps in penetration testing and reco
--
p 5 | a profile of the target organization.  Scanning refers to collecting more information using complex and aggressive reconnaissance techniques.    Types of Scanning  1. Network Scanning – Identifying active hosts and devices on a network.  2. Port Scanning – Finding open ports and services running on a target.  3. Vulnerability Scanning – Detecting s
--
p 7 | an inactive or blocked host.    • The corresponding command to do so is as follows –  nmap -sn 192.168.1.0/24           This command uses the -sn flag (ping scan).      Evasion techniques  To evade IDS, sometimes we need to change the way we scan. Some of the different ways we can use nmap to evade  detection are  a) Fragmenting packets  Fragmentin
--

In [35]:
new_tests = []
for q, kw, kind in tests:
    if q.startswith("Black hat"):
        kw = "malicious|unauthorized|unethical|without authorization|cybercriminal"
    if q.startswith("What type of cyber attack"):
        kw, kind = "", "unanswerable"
    if q.startswith("What is the first stage"):
        kw = "locate nodes"       # use this only if the PDF confirms it
    new_tests.append((q, kw, kind))
tests = new_tests
print(len(tests), "tests")

13 tests

In [36]:
tests = [t for t in tests if not t[0].startswith("What is the first stage")]
print(len(tests), "tests")

12 tests

In [37]:
df.to_csv("eval_final.csv", index=False)
m = df[df.type != "unanswerable"]
print("Routing (doc+general):", m.routed_right.mean())
print(df.groupby("type")[["plain_ok", "agent_ok"]].agg(["sum", "count"]))

Routing (doc+general): 0.9090909090909091
             plain_ok       agent_ok
                  sum count      sum count
type
doc                 5     8        5     8
general             1     3        3     3
unanswerable        2     2        2     2

In [38]:
fixed = []
for q, kw, kind in tests:
    if q.startswith("What is the first stage"):
        continue
    if q.startswith("Black hat"):
        kw = "malicious|unauthorized|unethical|without authorization|cybercriminal"
    if q.startswith("What type of cyber attack"):
        kw, kind = "", "unanswerable"
    fixed.append((q, kw, kind))
tests = fixed

print(len(tests), "tests")
for t in tests:
    print(t)

12 tests
('What accuracy did the model achieve?', '93', 'doc')
('Black hat hackers are?', 'malicious|unauthorized|unethical|without authorization|cybercriminal', 'doc')
('What type of cyber attack was conducted on Canada’s Parliament in September 2023?', '', 'unanswerable')
('Which tool is used for port and network scanning?', 'nmap', 'doc')
('What does the Red Team consist of?', 'ethical hackers', 'doc')
('Which ports should a firewall block to protect against enumeration?', '445|139', 'doc')
('What are insider attacks?', 'legitimate access|employees', 'doc')
('What is the capital of France?', 'paris', 'general')
('Who wrote Romeo and Juliet?', 'shakespeare', 'general')
('What is 12 times 12?', '144', 'general')
("What is the author's favourite food?", '', 'unanswerable')
('Whats is the weather on the day author was born', '', 'unanswerable')

In [39]:
import time, pandas as pd
rows = []

for i, (q, kw, kind) in enumerate(tests):
    t = time.time()
    p_ans = plain_rag(q)
    a_ans, steps, retries = run(q)
    rows.append({
        "type": kind, "question": q,
        "plain_ok": correct(p_ans, kw, kind),
        "agent_ok": correct(a_ans, kw, kind),
        "routed_right": ("direct" in steps) == (kind == "general"),
        "retries": retries,
        "path": " > ".join(steps),
        "plain_answer": p_ans, "agent_answer": a_ans,
    })
    print(f"{i+1}/{len(tests)} done in {time.time()-t:.0f}s")

df = pd.DataFrame(rows)
print(df[["type", "plain_ok", "agent_ok", "routed_right", "retries"]].groupby("type").mean())
df[["question", "path", "agent_ok", "agent_answer"]]

1/12 done in 3s
2/12 done in 10s
3/12 done in 4s
4/12 done in 3s
5/12 done in 6s
6/12 done in 7s
7/12 done in 4s
8/12 done in 2s
9/12 done in 2s
10/12 done in 2s
11/12 done in 2s
12/12 done in 5s
              plain_ok  agent_ok  routed_right  retries
type
doc           0.833333       1.0           1.0      1.0
general       0.333333       1.0           1.0      0.0
unanswerable  1.000000       1.0           0.0      0.0

,question,path,agent_ok,agent_answer
0,What accuracy did the model achieve?,route > retrieve > grade > generate,True,The model achieved an overall accuracy of 93%.
1,Black hat hackers are?,route > retrieve > grade > rewrite > retrieve ...,True,Black hat hackers are those who engage in unet...
2,What type of cyber attack was conducted on Can...,route > direct,True,I don't know the specific type of cyber attack...
3,Which tool is used for port and network scanning?,route > retrieve > grade > generate,True,Nmap is used for port and network scanning.
4,What does the Red Team consist of?,route > retrieve > grade > rewrite > retrieve ...,True,The Red Team consists of ethical hackers (offe...
5,Which ports should a firewall block to protect...,route > retrieve > grade > rewrite > retrieve ...,True,"Ports 137, 138, 139, and 445 should be blocked..."
6,What are insider attacks?,route > retrieve > grade > generate,True,Insider attacks are carried out by individuals...
7,What is the capital of France?,route > direct,True,The capital of France is Paris.
8,Who wrote Romeo and Juliet?,route > direct,True,William Shakespeare wrote Romeo and Juliet.
9,What is 12 times 12?,route > direct,True,144
10,What is the author's favourite food?,route > direct,True,I don't know the author's favorite food as I d...
11,Whats is the weather on the day author was born,route > direct,True,I don't know the specific weather on the day t...

In [40]:
df.to_csv("eval_final.csv", index=False)
m = df[df.type != "unanswerable"]
print("Routing (doc+general):", m.routed_right.sum(), "/", len(m))
print(df.groupby("type")[["plain_ok", "agent_ok"]].agg(["sum", "count"]))

Routing (doc+general): 9 / 9
             plain_ok       agent_ok
                  sum count      sum count
type
doc                 5     6        6     6
general             1     3        3     3
unanswerable        3     3        3     3